# Generated by Django 2.1.3 on 2019-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('friend_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sendemail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=100)),
                ('sendto', models.CharField(max_length=20)),
                ('_from', models.CharField(max_length=20)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('send_password', models.CharField(max_length=20)),
                ('send_email', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
